# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IceCreamFlavour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavour_name', models.CharField(max_length=255)),
                ('your_name', models.CharField(max_length=255)),
            ],
        ),
    ]
